// To update this file when a new patch comes out, just update the variable name to whatever it is in the code
// so you don't have to update every monster's line

// update this variable on new patch
const ac = {
  addNewMonster(name, data) {
    this[name] = data;
  },
};

ac.addNewMonster('ForgeA', {
  Name: 'Fire_Forge',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 86400,
  MonsterHPTotal: 420,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('ForgeB', {
  Name: 'Cinder_Forge',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 86400,
  MonsterHPTotal: 420,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('Bandit_Bob', {
  Name: 'Bandit_Bob',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 86400,
  MonsterHPTotal: 420,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('Crystal0', {
  Name: 'Crystal_Carrot',
  AFKtype: 'FIGHTING',
  MonsterFace: 1,
  MonsterOffsetX: 23,
  MonsterOffsetY: 23,
  HeightOfMonster: 68,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 15,
  RespawnTime: 35,
  MonsterHPTotal: 1,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 2,
  ExpType: 0,
  Defence: 150,
  MoveSPEED: 4,
  Damages: [0, 1],
});
ac.addNewMonster('Crystal1', {
  Name: 'Crystal_Crabal',
  AFKtype: 'FIGHTING',
  MonsterFace: 11,
  MonsterOffsetX: 38,
  MonsterOffsetY: 40,
  HeightOfMonster: 64,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 12,
  RespawnTime: 40,
  MonsterHPTotal: 7500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 210,
  ExpType: 0,
  Defence: 180,
  MoveSPEED: 4,
  Damages: [1, 1],
});
ac.addNewMonster('Crystal2', {
  Name: 'Crystal_Cattle',
  AFKtype: 'FIGHTING',
  MonsterFace: 47,
  MonsterOffsetX: 38,
  MonsterOffsetY: 40,
  HeightOfMonster: 47,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 17,
  RespawnTime: 252e3,
  MonsterHPTotal: 1e6,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 210,
  ExpType: 0,
  Defence: 180,
  MoveSPEED: 5,
  Damages: [1, 1],
});
ac.addNewMonster('mushG', {
  Name: 'Green_Mushroom',
  AFKtype: 'FIGHTING',
  MonsterFace: 1,
  MonsterOffsetX: 23,
  MonsterOffsetY: 23,
  HeightOfMonster: 50,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 12,
  RespawnTime: 35,
  MonsterHPTotal: 10,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 2,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 4,
  Damages: [1, 1],
});
ac.addNewMonster('frogG', {
  Name: 'Frog',
  AFKtype: 'FIGHTING',
  MonsterFace: 14,
  MonsterOffsetX: 38,
  MonsterOffsetY: 43,
  HeightOfMonster: 30,
  MonsterMoving: 1,
  MovingFrame: 5,
  DeathFrame: 12,
  RespawnTime: 40,
  MonsterHPTotal: 50,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 7,
  ExpType: 0,
  Defence: 2,
  MoveSPEED: 4,
  Damages: [5, 1],
});
ac.addNewMonster('beanG', {
  Name: 'Bored_Bean',
  AFKtype: 'FIGHTING',
  MonsterFace: 7,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 50,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 15,
  RespawnTime: 50,
  MonsterHPTotal: 150,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 15,
  ExpType: 0,
  Defence: 4,
  MoveSPEED: 4,
  Damages: [14, 1],
});
ac.addNewMonster('slimeG', {
  Name: 'Slime',
  AFKtype: 'FIGHTING',
  MonsterFace: 24,
  MonsterOffsetX: 22,
  MonsterOffsetY: 38,
  HeightOfMonster: 25,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 42,
  MonsterHPTotal: 250,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 23,
  ExpType: 0,
  Defence: 9,
  MoveSPEED: 4,
  Damages: [17, 1],
});
ac.addNewMonster('snakeG', {
  Name: 'Baby_Boa',
  AFKtype: 'FIGHTING',
  MonsterFace: 25,
  MonsterOffsetX: 38,
  MonsterOffsetY: 36,
  HeightOfMonster: 32,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 13,
  RespawnTime: 45,
  MonsterHPTotal: 450,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 34,
  ExpType: 0,
  Defence: 18,
  MoveSPEED: 8,
  Damages: [22, 1],
});
ac.addNewMonster('carrotO', {
  Name: 'Carrotman',
  AFKtype: 'FIGHTING',
  MonsterFace: 9,
  MonsterOffsetX: 38,
  MonsterOffsetY: 45,
  HeightOfMonster: 50,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 15,
  RespawnTime: 50,
  MonsterHPTotal: 800,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 45,
  ExpType: 0,
  Defence: 30,
  MoveSPEED: 6,
  Damages: [26, 1],
});
ac.addNewMonster('goblinG', {
  Name: 'Glublin',
  AFKtype: 'FIGHTING',
  MonsterFace: 15,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 50,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 15,
  RespawnTime: 52,
  MonsterHPTotal: 1250,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 60,
  ExpType: 0,
  Defence: 52,
  MoveSPEED: 4,
  Damages: [35, 1],
});
ac.addNewMonster('plank', {
  Name: 'Wode_Board',
  AFKtype: 'FIGHTING',
  MonsterFace: 3,
  MonsterOffsetX: 38,
  MonsterOffsetY: 58,
  HeightOfMonster: 46,
  MonsterMoving: 1,
  MovingFrame: 5,
  DeathFrame: 19,
  RespawnTime: 45,
  MonsterHPTotal: 1800,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 75,
  ExpType: 0,
  Defence: 70,
  MoveSPEED: 3,
  Damages: [40, 1],
});
ac.addNewMonster('frogBIG', {
  Name: 'Gigafrog',
  AFKtype: 'FIGHTING',
  MonsterFace: 13,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 26,
  MonsterMoving: 1,
  MovingFrame: 8,
  DeathFrame: 16,
  RespawnTime: 55,
  MonsterHPTotal: 2500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 95,
  ExpType: 0,
  Defence: 120,
  MoveSPEED: 3,
  Damages: [60, 1],
});
ac.addNewMonster('branch', {
  Name: 'Walking_Stick',
  AFKtype: 'FIGHTING',
  MonsterFace: 8,
  MonsterOffsetX: 32,
  MonsterOffsetY: 20,
  HeightOfMonster: 50,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 15,
  RespawnTime: 60,
  MonsterHPTotal: 1500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 120,
  ExpType: 0,
  Defence: 150,
  MoveSPEED: 4,
  Damages: [20, 1],
});
ac.addNewMonster('acorn', {
  Name: 'Nutto',
  AFKtype: 'FIGHTING',
  MonsterFace: 5,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 42,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 60,
  MonsterHPTotal: 4e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 190,
  ExpType: 0,
  Defence: 200,
  MoveSPEED: 5,
  Damages: [40, 1],
});
ac.addNewMonster('mushW', {
  Name: 'Wood_Mushroom',
  AFKtype: 'FIGHTING',
  MonsterFace: 34,
  MonsterOffsetX: 23,
  MonsterOffsetY: 25,
  HeightOfMonster: 50,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 14,
  RespawnTime: 50,
  MonsterHPTotal: 1e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 300,
  ExpType: 0,
  Defence: 500,
  MoveSPEED: 4,
  Damages: [75, 1],
});
ac.addNewMonster('poopSmall', {
  Name: 'Poop',
  AFKtype: 'FIGHTING',
  MonsterFace: 20,
  MonsterOffsetX: 22,
  MonsterOffsetY: 30,
  HeightOfMonster: 32,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 12,
  RespawnTime: 60,
  MonsterHPTotal: 9e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 220,
  ExpType: 0,
  Defence: 100,
  MoveSPEED: 4,
  Damages: [150, 1],
});
ac.addNewMonster('ratB', {
  Name: 'Rat',
  AFKtype: 'FIGHTING',
  MonsterFace: 22,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 32,
  MonsterMoving: 1,
  MovingFrame: 9,
  DeathFrame: 18,
  RespawnTime: 60,
  MonsterHPTotal: 2e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 330,
  ExpType: 0,
  Defence: 180,
  MoveSPEED: 8,
  Damages: [220, 1],
});
ac.addNewMonster('poopD', {
  Name: 'Boop',
  AFKtype: 'FIGHTING',
  MonsterFace: 33,
  MonsterOffsetX: 22,
  MonsterOffsetY: 30,
  HeightOfMonster: 34,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 12,
  RespawnTime: 74500,
  MonsterHPTotal: 2e5,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 1e3,
  ExpType: 0,
  Defence: 120,
  MoveSPEED: 3,
  Damages: [250, 1],
});
ac.addNewMonster('rockG', {
  Name: 'Healing_Rune',
  AFKtype: 'FIGHTING',
  MonsterFace: 13,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 42,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 55,
  MonsterHPTotal: 3e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 150,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [50, 1],
});
ac.addNewMonster('rockB', {
  Name: 'Shielding_Rune',
  AFKtype: 'FIGHTING',
  MonsterFace: 13,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 42,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 55,
  MonsterHPTotal: 3e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 150,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [50, 1],
});
ac.addNewMonster('rockS', {
  Name: 'Skeleton_Rune',
  AFKtype: 'FIGHTING',
  MonsterFace: 13,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 42,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 55,
  MonsterHPTotal: 2e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 10,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [50, 1],
});
ac.addNewMonster('jarSand', {
  Name: 'Sandy_Pot',
  AFKtype: 'FIGHTING',
  MonsterFace: 16,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 32,
  MonsterMoving: 1,
  MovingFrame: 5,
  DeathFrame: 15,
  RespawnTime: 50,
  MonsterHPTotal: 4e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 150,
  ExpType: 0,
  Defence: 125,
  MoveSPEED: 5,
  Damages: [70, 1],
});
ac.addNewMonster('mimicA', {
  Name: 'Mimic',
  AFKtype: 'FIGHTING',
  MonsterFace: 17,
  MonsterOffsetX: 38,
  MonsterOffsetY: 38,
  HeightOfMonster: 48,
  MonsterMoving: 1,
  MovingFrame: 9,
  DeathFrame: 19,
  RespawnTime: 50,
  MonsterHPTotal: 5500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 180,
  ExpType: 0,
  Defence: 145,
  MoveSPEED: 4,
  Damages: [85, 1],
});
ac.addNewMonster('crabcake', {
  Name: 'Crabcake',
  AFKtype: 'FIGHTING',
  MonsterFace: 11,
  MonsterOffsetX: 38,
  MonsterOffsetY: 40,
  HeightOfMonster: 64,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 12,
  RespawnTime: 40,
  MonsterHPTotal: 7500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 210,
  ExpType: 0,
  Defence: 180,
  MoveSPEED: 4,
  Damages: [92, 1],
});
ac.addNewMonster('coconut', {
  Name: 'Mafioso',
  AFKtype: 'FIGHTING',
  MonsterFace: 10,
  MonsterOffsetX: 38,
  MonsterOffsetY: 55,
  HeightOfMonster: 44,
  MonsterMoving: 1,
  MovingFrame: 15,
  DeathFrame: 26,
  RespawnTime: 40,
  MonsterHPTotal: 11e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 240,
  ExpType: 0,
  Defence: 240,
  MoveSPEED: 4,
  Damages: [115, 1],
});
ac.addNewMonster('sandcastle', {
  Name: 'Sand_Castle',
  AFKtype: 'FIGHTING',
  MonsterFace: 28,
  MonsterOffsetX: 50,
  MonsterOffsetY: 59,
  HeightOfMonster: 34,
  MonsterMoving: 1,
  MovingFrame: 9,
  DeathFrame: 19,
  RespawnTime: 40,
  MonsterHPTotal: 13e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 265,
  ExpType: 0,
  Defence: 270,
  MoveSPEED: 3,
  Damages: [125, 1],
});
ac.addNewMonster('pincermin', {
  Name: 'Pincermin',
  AFKtype: 'FIGHTING',
  MonsterFace: 2,
  MonsterOffsetX: 22,
  MonsterOffsetY: 42,
  HeightOfMonster: 82,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 50,
  MonsterHPTotal: 15500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 290,
  ExpType: 0,
  Defence: 300,
  MoveSPEED: 5,
  Damages: [140, 1],
});
ac.addNewMonster('potato', {
  Name: 'Mashed_Potato',
  AFKtype: 'FIGHTING',
  MonsterFace: 21,
  MonsterOffsetX: 50,
  MonsterOffsetY: 34,
  HeightOfMonster: 89,
  MonsterMoving: 1,
  MovingFrame: 7,
  DeathFrame: 17,
  RespawnTime: 40,
  MonsterHPTotal: 18500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 310,
  ExpType: 0,
  Defence: 330,
  MoveSPEED: 6,
  Damages: [160, 1],
});
ac.addNewMonster('steak', {
  Name: 'Tyson',
  AFKtype: 'FIGHTING',
  MonsterFace: 31,
  MonsterOffsetX: 50,
  MonsterOffsetY: 72,
  HeightOfMonster: 62,
  MonsterMoving: 1,
  MovingFrame: 7,
  DeathFrame: 14,
  RespawnTime: 40,
  MonsterHPTotal: 23e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 350,
  ExpType: 0,
  Defence: 450,
  MoveSPEED: 5,
  Damages: [220, 1],
});
ac.addNewMonster('moonman', {
  Name: 'Moonmoon',
  AFKtype: 'FIGHTING',
  MonsterFace: 30,
  MonsterOffsetX: 50,
  MonsterOffsetY: 66,
  HeightOfMonster: 54,
  MonsterMoving: 1,
  MovingFrame: 7,
  DeathFrame: 16,
  RespawnTime: 40,
  MonsterHPTotal: 26500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 380,
  ExpType: 0,
  Defence: 500,
  MoveSPEED: 5,
  Damages: [240, 1],
});
ac.addNewMonster('sandgiant', {
  Name: 'Sand_Giant',
  AFKtype: 'FIGHTING',
  MonsterFace: 29,
  MonsterOffsetX: 50,
  MonsterOffsetY: 72,
  HeightOfMonster: 44,
  MonsterMoving: 1,
  MovingFrame: 9,
  DeathFrame: 20,
  RespawnTime: 40,
  MonsterHPTotal: 3e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 410,
  ExpType: 0,
  Defence: 550,
  MoveSPEED: 3,
  Damages: [260, 1],
});
ac.addNewMonster('snailZ', {
  Name: 'Snelbie',
  AFKtype: 'FIGHTING',
  MonsterFace: 27,
  MonsterOffsetX: 50,
  MonsterOffsetY: 72,
  HeightOfMonster: 54,
  MonsterMoving: 1,
  MovingFrame: 8,
  DeathFrame: 18,
  RespawnTime: 40,
  MonsterHPTotal: 35e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 460,
  ExpType: 0,
  Defence: 650,
  MoveSPEED: 4,
  Damages: [300, 1],
});
ac.addNewMonster('sheep', {
  Name: 'Sheepie',
  AFKtype: 'FIGHTING',
  MonsterFace: 35,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 47,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 17,
  RespawnTime: 40,
  MonsterHPTotal: 55e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 620,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 4,
  Damages: [0, 1],
});
ac.addNewMonster('flake', {
  Name: 'Frost_Flake',
  AFKtype: 'FIGHTING',
  MonsterFace: 36,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 44,
  MonsterMoving: 1,
  MovingFrame: 0,
  DeathFrame: 10,
  RespawnTime: 40,
  MonsterHPTotal: 67e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 700,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 4,
  Damages: [0, 1],
});
ac.addNewMonster('stache', {
  Name: 'Sir_Stache',
  AFKtype: 'FIGHTING',
  MonsterFace: 37,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 70,
  MonsterMoving: 1,
  MovingFrame: 0,
  DeathFrame: 10,
  RespawnTime: 40,
  MonsterHPTotal: 81e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 800,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 4,
  Damages: [0, 1],
});
ac.addNewMonster('ram', {
  Name: 'Dedotated_Ram',
  AFKtype: 'FIGHTING',
  MonsterFace: 46,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 62,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 13,
  RespawnTime: 40,
  MonsterHPTotal: 25e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 1900,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 6,
  Damages: [100, 1],
});
ac.addNewMonster('bloque', {
  Name: 'Bloque',
  AFKtype: 'FIGHTING',
  MonsterFace: 32,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 42,
  MonsterMoving: 1,
  MovingFrame: 7,
  DeathFrame: 16,
  RespawnTime: 40,
  MonsterHPTotal: 1e5,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 940,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 4,
  Damages: [0, 1],
});
ac.addNewMonster('mamoth', {
  Name: 'mamooth',
  AFKtype: 'FIGHTING',
  MonsterFace: 38,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 40,
  MonsterMoving: 1,
  MovingFrame: 7,
  DeathFrame: 16,
  RespawnTime: 40,
  MonsterHPTotal: 115e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 1030,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 3,
  Damages: [0, 1],
});
ac.addNewMonster('snowball', {
  Name: 'Snowman',
  AFKtype: 'FIGHTING',
  MonsterFace: 39,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 50,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 15,
  RespawnTime: 40,
  MonsterHPTotal: 13e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 1130,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 6,
  Damages: [0, 1],
});
ac.addNewMonster('penguin', {
  Name: 'Penguin',
  AFKtype: 'FIGHTING',
  MonsterFace: 40,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 48,
  MonsterMoving: 1,
  MovingFrame: 14,
  DeathFrame: 25,
  RespawnTime: 40,
  MonsterHPTotal: 15e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 1250,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 4,
  Damages: [0, 1],
});
ac.addNewMonster('thermostat', {
  Name: 'Thermister',
  AFKtype: 'FIGHTING',
  MonsterFace: 41,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 68,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 20,
  RespawnTime: 40,
  MonsterHPTotal: 175e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 1370,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 4,
  Damages: [0, 1],
});
ac.addNewMonster('glass', {
  Name: 'Quenchie',
  AFKtype: 'FIGHTING',
  MonsterFace: 42,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 44,
  MonsterMoving: 1,
  MovingFrame: 10,
  DeathFrame: 23,
  RespawnTime: 40,
  MonsterHPTotal: 215e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 1570,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 4,
  Damages: [0, 1],
});
ac.addNewMonster('snakeB', {
  Name: 'Cryosnake',
  AFKtype: 'FIGHTING',
  MonsterFace: 43,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 36,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 13,
  RespawnTime: 40,
  MonsterHPTotal: 24e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 1690,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 6,
  Damages: [0, 1],
});
ac.addNewMonster('speaker', {
  Name: 'Bop_Box',
  AFKtype: 'FIGHTING',
  MonsterFace: 44,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 50,
  MonsterMoving: 1,
  MovingFrame: 12,
  DeathFrame: 23,
  RespawnTime: 40,
  MonsterHPTotal: 27e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 1780,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 4,
  Damages: [0, 1],
});
ac.addNewMonster('eye', {
  Name: 'Neyeptune',
  AFKtype: 'FIGHTING',
  MonsterFace: 45,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 44,
  MonsterMoving: 1,
  MovingFrame: 0,
  DeathFrame: 12,
  RespawnTime: 40,
  MonsterHPTotal: 3e5,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 1900,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 4,
  Damages: [0, 1],
});
ac.addNewMonster('mushR', {
  Name: 'Red_Mushroom',
  AFKtype: 'FIGHTING',
  MonsterFace: 19,
  MonsterOffsetX: 23,
  MonsterOffsetY: 25,
  HeightOfMonster: 50,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 12,
  RespawnTime: 45,
  MonsterHPTotal: 1e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 47,
  ExpType: 0,
  Defence: 25,
  MoveSPEED: 4,
  Damages: [30, 1],
});
ac.addNewMonster('shovelR', {
  Name: 'Dig_Doug',
  AFKtype: 'FIGHTING',
  MonsterFace: 23,
  MonsterOffsetX: 38,
  MonsterOffsetY: 47,
  HeightOfMonster: 56,
  MonsterMoving: 1,
  MovingFrame: 5,
  DeathFrame: 16,
  RespawnTime: 40,
  MonsterHPTotal: 14e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 420,
  ExpType: 0,
  Defence: 228,
  MoveSPEED: 4,
  Damages: [2, 1],
});
ac.addNewMonster('skele', {
  Name: 'Xylobone',
  AFKtype: 'FIGHTING',
  MonsterFace: 23,
  MonsterOffsetX: 38,
  MonsterOffsetY: 47,
  HeightOfMonster: 56,
  MonsterMoving: 1,
  MovingFrame: 8,
  DeathFrame: 20,
  RespawnTime: 40,
  MonsterHPTotal: 14e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 420,
  ExpType: 0,
  Defence: 228,
  MoveSPEED: 4,
  Damages: [2, 1],
});
ac.addNewMonster('skele2', {
  Name: 'Bloodbone',
  AFKtype: 'FIGHTING',
  MonsterFace: 23,
  MonsterOffsetX: 38,
  MonsterOffsetY: 47,
  HeightOfMonster: 56,
  MonsterMoving: 1,
  MovingFrame: 8,
  DeathFrame: 20,
  RespawnTime: 40,
  MonsterHPTotal: 14e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 420,
  ExpType: 0,
  Defence: 228,
  MoveSPEED: 4,
  Damages: [2, 1],
});
ac.addNewMonster('wolfA', {
  Name: 'Amarok',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 86400,
  MonsterHPTotal: 25e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 105,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('wolfB', {
  Name: 'Chaotic_Amarok',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 86400,
  MonsterHPTotal: 15e6,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 1750,
  MoveSPEED: 3,
  Damages: [1200, 1],
});
ac.addNewMonster('wolfC', {
  Name: 'Nightmare_Amarok',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 86400,
  MonsterHPTotal: 75e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('Boss2A', {
  Name: 'Efaunt',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 86400,
  MonsterHPTotal: 1e6,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 775,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('Boss2B', {
  Name: 'Chaotic_Efaunt',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 86400,
  MonsterHPTotal: 1e8,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 4e3,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('Boss2C', {
  Name: 'Nightmare_Amarok',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 86400,
  MonsterHPTotal: 75e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('poopBig', {
  Name: 'Dr_Defecaus',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 74500,
  MonsterHPTotal: 75e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('babayaga', {
  Name: 'Baba_Yaga',
  AFKtype: 'FIGHTING',
  MonsterFace: 6,
  MonsterOffsetX: 42,
  MonsterOffsetY: 40,
  HeightOfMonster: 92,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 15,
  RespawnTime: 86400,
  MonsterHPTotal: 15e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 1750,
  ExpType: 0,
  Defence: 300,
  MoveSPEED: 4,
  Damages: [400, 20],
});
ac.addNewMonster('babaHour', {
  Name: 'Biggie_Hours',
  AFKtype: 'FIGHTING',
  MonsterFace: 6,
  MonsterOffsetX: 42,
  MonsterOffsetY: 40,
  HeightOfMonster: 86,
  MonsterMoving: 1,
  MovingFrame: 8,
  DeathFrame: 20,
  RespawnTime: 86400,
  MonsterHPTotal: 8e5,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12500,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 5,
  Damages: [500, 20],
});
ac.addNewMonster('babaMummy', {
  Name: 'King_Doot',
  AFKtype: 'FIGHTING',
  MonsterFace: 6,
  MonsterOffsetX: 42,
  MonsterOffsetY: 40,
  HeightOfMonster: 102,
  MonsterMoving: 1,
  MovingFrame: 8,
  DeathFrame: 17,
  RespawnTime: 86400,
  MonsterHPTotal: 3e6,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 5e4,
  ExpType: 0,
  Defence: 1e3,
  MoveSPEED: 4,
  Damages: [800, 450],
});
ac.addNewMonster('xmasEvent', {
  Name: 'Giftmas_Blobulyte',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 86400,
  MonsterHPTotal: 75e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('xmasEvent2', {
  Name: 'Meaning_of_Giftmas',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 86400,
  MonsterHPTotal: 75e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('loveEvent', {
  Name: 'Loveulyte',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 86400,
  MonsterHPTotal: 75e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('loveEvent2', {
  Name: 'Chocco_Box',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 86400,
  MonsterHPTotal: 75e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('EasterEvent1', {
  Name: 'Egggulyte',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 86400,
  MonsterHPTotal: 75e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('EasterEvent2', {
  Name: 'Egg_Capsule',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 86400,
  MonsterHPTotal: 75e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('Blank0ramaFiller', {
  Name: 'Nightmare_Amarok',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 85,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 13,
  RespawnTime: 86400,
  MonsterHPTotal: 75e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('ghost', {
  Name: 'Ghost',
  AFKtype: 'FIGHTING',
  MonsterFace: 6,
  MonsterOffsetX: 42,
  MonsterOffsetY: 40,
  HeightOfMonster: 52,
  MonsterMoving: 1,
  MovingFrame: 7,
  DeathFrame: 16,
  RespawnTime: 100,
  MonsterHPTotal: 1e3,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 1,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 5,
  Damages: [5, 5],
});
ac.addNewMonster('slimeR', {
  Name: 'Valentslime',
  AFKtype: 'FIGHTING',
  MonsterFace: 24,
  MonsterOffsetX: 22,
  MonsterOffsetY: 38,
  HeightOfMonster: 32,
  MonsterMoving: 1,
  MovingFrame: 8,
  DeathFrame: 16,
  RespawnTime: 42,
  MonsterHPTotal: 500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 20,
  ExpType: 0,
  Defence: 9,
  MoveSPEED: 4,
  Damages: [1, 1],
});
ac.addNewMonster('sheepB', {
  Name: 'Floofie',
  AFKtype: 'FIGHTING',
  MonsterFace: 35,
  MonsterOffsetX: 38,
  MonsterOffsetY: 32,
  HeightOfMonster: 47,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 17,
  RespawnTime: 40,
  MonsterHPTotal: 500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 1,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 5,
  Damages: [0, 1],
});
ac.addNewMonster('snakeY', {
  Name: 'Shell_Snake',
  AFKtype: 'FIGHTING',
  MonsterFace: 25,
  MonsterOffsetX: 38,
  MonsterOffsetY: 36,
  HeightOfMonster: 32,
  MonsterMoving: 1,
  MovingFrame: 6,
  DeathFrame: 13,
  RespawnTime: 45,
  MonsterHPTotal: 450,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 34,
  ExpType: 0,
  Defence: 18,
  MoveSPEED: 8,
  Damages: [22, 1],
});
ac.addNewMonster('Copper', {
  Name: 'Copper',
  AFKtype: 'MINING',
  MonsterFace: 0,
  MonsterOffsetX: 22,
  MonsterOffsetY: 38,
  HeightOfMonster: 25,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 120,
  MonsterHPTotal: 5,
  Type: ac.ORE_TYPE,
  SpecialType: '_',
  ExpGiven: 2,
  ExpType: 1,
  Defence: 30,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('Iron', {
  Name: 'Iron',
  AFKtype: 'MINING',
  MonsterFace: 0,
  MonsterOffsetX: 22,
  MonsterOffsetY: 38,
  HeightOfMonster: 25,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 120,
  MonsterHPTotal: 5,
  Type: ac.ORE_TYPE,
  SpecialType: '_',
  ExpGiven: 5,
  ExpType: 1,
  Defence: 200,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('Gold', {
  Name: 'Gold',
  AFKtype: 'MINING',
  MonsterFace: 0,
  MonsterOffsetX: 22,
  MonsterOffsetY: 38,
  HeightOfMonster: 25,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 120,
  MonsterHPTotal: 5,
  Type: ac.ORE_TYPE,
  SpecialType: '_',
  ExpGiven: 10,
  ExpType: 1,
  Defence: 1500,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('Plat', {
  Name: 'Plat',
  AFKtype: 'MINING',
  MonsterFace: 0,
  MonsterOffsetX: 22,
  MonsterOffsetY: 38,
  HeightOfMonster: 25,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 180,
  MonsterHPTotal: 5,
  Type: ac.ORE_TYPE,
  SpecialType: '_',
  ExpGiven: 30,
  ExpType: 1,
  Defence: 2e4,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('Dementia', {
  Name: 'Dementia',
  AFKtype: 'MINING',
  MonsterFace: 0,
  MonsterOffsetX: 22,
  MonsterOffsetY: 38,
  HeightOfMonster: 25,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 180,
  MonsterHPTotal: 5,
  Type: ac.ORE_TYPE,
  SpecialType: '_',
  ExpGiven: 55,
  ExpType: 1,
  Defence: 175e3,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('Void', {
  Name: 'Void',
  AFKtype: 'MINING',
  MonsterFace: 0,
  MonsterOffsetX: 22,
  MonsterOffsetY: 38,
  HeightOfMonster: 25,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 240,
  MonsterHPTotal: 5,
  Type: ac.ORE_TYPE,
  SpecialType: '_',
  ExpGiven: 185,
  ExpType: 1,
  Defence: 6e5,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('Lustre', {
  Name: 'Lustre',
  AFKtype: 'MINING',
  MonsterFace: 0,
  MonsterOffsetX: 22,
  MonsterOffsetY: 38,
  HeightOfMonster: 25,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 240,
  MonsterHPTotal: 5,
  Type: ac.ORE_TYPE,
  SpecialType: '_',
  ExpGiven: 250,
  ExpType: 1,
  Defence: 2e6,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('Starfire', {
  Name: 'Starfire',
  AFKtype: 'MINING',
  MonsterFace: 0,
  MonsterOffsetX: 22,
  MonsterOffsetY: 38,
  HeightOfMonster: 25,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 240,
  MonsterHPTotal: 5,
  Type: ac.ORE_TYPE,
  SpecialType: '_',
  ExpGiven: 500,
  ExpType: 1,
  Defence: 5e6,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('Dreadlo', {
  Name: 'Dreadlo',
  AFKtype: 'MINING',
  MonsterFace: 0,
  MonsterOffsetX: 22,
  MonsterOffsetY: 38,
  HeightOfMonster: 25,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 300,
  MonsterHPTotal: 5,
  Type: ac.ORE_TYPE,
  SpecialType: '_',
  ExpGiven: 850,
  ExpType: 1,
  Defence: 25e6,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('Godshard', {
  Name: 'Godshard',
  AFKtype: 'MINING',
  MonsterFace: 0,
  MonsterOffsetX: 22,
  MonsterOffsetY: 38,
  HeightOfMonster: 25,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 600,
  MonsterHPTotal: 5,
  Type: ac.ORE_TYPE,
  SpecialType: '_',
  ExpGiven: 1250,
  ExpType: 1,
  Defence: 1e8,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('OakTree', {
  Name: 'Oak_Tree',
  AFKtype: 'CHOPPIN',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 0,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 1,
  DeathFrame: 2,
  RespawnTime: 0,
  MonsterHPTotal: 5,
  Type: ac.TREE_TYPE,
  SpecialType: '_',
  ExpGiven: 2,
  ExpType: 3,
  Defence: 20,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('BirchTree', {
  Name: 'Birch_Tree',
  AFKtype: 'CHOPPIN',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 0,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 1,
  DeathFrame: 5,
  RespawnTime: 0,
  MonsterHPTotal: 5,
  Type: ac.TREE_TYPE,
  SpecialType: '_',
  ExpGiven: 6,
  ExpType: 3,
  Defence: 80,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('JungleTree', {
  Name: 'Jungle_Tree',
  AFKtype: 'CHOPPIN',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 0,
  HeightOfMonster: 112,
  MonsterMoving: 0,
  MovingFrame: 1,
  DeathFrame: 7,
  RespawnTime: 0,
  MonsterHPTotal: 5,
  Type: ac.TREE_TYPE,
  SpecialType: '_',
  ExpGiven: 12,
  ExpType: 3,
  Defence: 250,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ForestTree', {
  Name: 'Forest_Tree',
  AFKtype: 'CHOPPIN',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 0,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 1,
  DeathFrame: 8,
  RespawnTime: 0,
  MonsterHPTotal: 5,
  Type: ac.TREE_TYPE,
  SpecialType: '_',
  ExpGiven: 20,
  ExpType: 3,
  Defence: 600,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ToiletTree', {
  Name: 'Toilet_Tree',
  AFKtype: 'CHOPPIN',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 0,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 1,
  DeathFrame: 3,
  RespawnTime: 0,
  MonsterHPTotal: 5,
  Type: ac.TREE_TYPE,
  SpecialType: '_',
  ExpGiven: 50,
  ExpType: 3,
  Defence: 3500,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('PalmTree', {
  Name: 'Palm_Tree',
  AFKtype: 'CHOPPIN',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 0,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 2,
  DeathFrame: 1,
  RespawnTime: 0,
  MonsterHPTotal: 5,
  Type: ac.TREE_TYPE,
  SpecialType: '_',
  ExpGiven: 32,
  ExpType: 3,
  Defence: 1250,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('StumpTree', {
  Name: 'Stump_Tree',
  AFKtype: 'CHOPPIN',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 0,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 1,
  DeathFrame: 4,
  RespawnTime: 0,
  MonsterHPTotal: 5,
  Type: ac.TREE_TYPE,
  SpecialType: '_',
  ExpGiven: 90,
  ExpType: 3,
  Defence: 1e4,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('SaharanFoal', {
  Name: 'Saharan_Foal',
  AFKtype: 'CHOPPIN',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 0,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 3,
  DeathFrame: 0,
  RespawnTime: 0,
  MonsterHPTotal: 5,
  Type: ac.TREE_TYPE,
  SpecialType: '_',
  ExpGiven: 2,
  ExpType: 3,
  Defence: 20,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('AlienTree', {
  Name: 'Alien_Tree',
  AFKtype: 'CHOPPIN',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 0,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 1,
  DeathFrame: 6,
  RespawnTime: 0,
  MonsterHPTotal: 5,
  Type: ac.TREE_TYPE,
  SpecialType: '_',
  ExpGiven: 6,
  ExpType: 3,
  Defence: 2e4,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('FishSmall', {
  Name: 'Small_Fish',
  AFKtype: 'FISHING',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 50,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 1,
  DeathFrame: 2,
  RespawnTime: 0,
  MonsterHPTotal: 5,
  Type: ac.FISH_TYPE,
  SpecialType: '_',
  ExpGiven: 2,
  ExpType: 4,
  Defence: 40,
  MoveSPEED: 0,
  Damages: [6, 1],
});
ac.addNewMonster('Fish1', {
  Name: 'Goldfish',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 48,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 0,
  RespawnTime: 86400,
  MonsterHPTotal: 75e4,
  Type: ac.FISH_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('Fish2', {
  Name: 'Hermit_Can',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 48,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 1,
  RespawnTime: 86400,
  MonsterHPTotal: 75e4,
  Type: ac.FISH_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('Fish3', {
  Name: 'Jellyfish',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 48,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 2,
  RespawnTime: 86400,
  MonsterHPTotal: 75e4,
  Type: ac.FISH_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('Fish4', {
  Name: 'Bloach',
  AFKtype: 'FIGHTING',
  MonsterFace: 4,
  MonsterOffsetX: 42,
  MonsterOffsetY: 28,
  HeightOfMonster: 48,
  MonsterMoving: 1,
  MovingFrame: 4,
  DeathFrame: 3,
  RespawnTime: 86400,
  MonsterHPTotal: 75e4,
  Type: ac.FISH_TYPE,
  SpecialType: 'a',
  ExpGiven: 12e3,
  ExpType: 0,
  Defence: 600,
  MoveSPEED: 3,
  Damages: [1e3, 1],
});
ac.addNewMonster('BugNest1', {
  Name: 'Fly_Nest',
  AFKtype: 'FIGHTING',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 30,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 51,
  DeathFrame: 0,
  RespawnTime: 86400,
  MonsterHPTotal: 999999999,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 2,
  ExpType: 6,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [6, 1],
});
ac.addNewMonster('BugNest2', {
  Name: 'Butterfly_Bar',
  AFKtype: 'FIGHTING',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 30,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 67,
  DeathFrame: 1,
  RespawnTime: 86400,
  MonsterHPTotal: 999999999,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 2,
  ExpType: 6,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [6, 1],
});
ac.addNewMonster('BugNest3', {
  Name: 'Sentient_Bowl',
  AFKtype: 'FIGHTING',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 30,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 59,
  DeathFrame: 2,
  RespawnTime: 86400,
  MonsterHPTotal: 999999999,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 2,
  ExpType: 6,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [6, 1],
});
ac.addNewMonster('BugNest4', {
  Name: 'Grocery_Bag',
  AFKtype: 'FIGHTING',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 30,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 63,
  DeathFrame: 3,
  RespawnTime: 86400,
  MonsterHPTotal: 999999999,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 2,
  ExpType: 6,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [6, 1],
});
ac.addNewMonster('Bug1', {
  Name: 'Flies',
  AFKtype: 'CATCHING',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 50,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 1,
  DeathFrame: 0,
  RespawnTime: 0,
  MonsterHPTotal: 5,
  Type: ac.BUG_TYPE,
  SpecialType: '_',
  ExpGiven: 2,
  ExpType: 6,
  Defence: 50,
  MoveSPEED: 0,
  Damages: [6, 1],
});
ac.addNewMonster('Bug2', {
  Name: 'Butterflies',
  AFKtype: 'CATCHING',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 50,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 1,
  DeathFrame: 1,
  RespawnTime: 0,
  MonsterHPTotal: 5,
  Type: ac.BUG_TYPE,
  SpecialType: '_',
  ExpGiven: 6,
  ExpType: 6,
  Defence: 600,
  MoveSPEED: 0,
  Damages: [6, 1],
});
ac.addNewMonster('Bug3', {
  Name: 'Sentient_Cereal',
  AFKtype: 'CATCHING',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 50,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 1,
  DeathFrame: 2,
  RespawnTime: 0,
  MonsterHPTotal: 5,
  Type: ac.BUG_TYPE,
  SpecialType: '_',
  ExpGiven: 10,
  ExpType: 6,
  Defence: 2500,
  MoveSPEED: 0,
  Damages: [6, 1],
});
ac.addNewMonster('Bug4', {
  Name: 'Fruitflies',
  AFKtype: 'CATCHING',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 50,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 1,
  DeathFrame: 3,
  RespawnTime: 0,
  MonsterHPTotal: 5,
  Type: ac.BUG_TYPE,
  SpecialType: '_',
  ExpGiven: 20,
  ExpType: 6,
  Defence: 7e3,
  MoveSPEED: 0,
  Damages: [6, 1],
});
ac.addNewMonster('BossPart', {
  Name: 'Error',
  AFKtype: 'FIGHTING',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 50,
  MonsterMoving: 0,
  MovingFrame: 4,
  DeathFrame: -1,
  RespawnTime: 22,
  MonsterHPTotal: 69420,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 4,
  Damages: [20, 1],
});
ac.addNewMonster('EfauntArm', {
  Name: 'Error',
  AFKtype: 'FIGHTING',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 50,
  MonsterMoving: 0,
  MovingFrame: 4,
  DeathFrame: 0,
  RespawnTime: 22,
  MonsterHPTotal: 69420,
  Type: ac.MONSTER_TYPE,
  SpecialType: 'a',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 4,
  Damages: [20, 1],
});
ac.addNewMonster('ChestA1', {
  Name: 'Bronze_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 18e3,
  MonsterHPTotal: 10,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestB1', {
  Name: 'Silver_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 36e3,
  MonsterHPTotal: 500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestC1', {
  Name: 'Golden_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 86400,
  MonsterHPTotal: 2e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestD1', {
  Name: 'Legendary_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 345600,
  MonsterHPTotal: 1e5,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestA2', {
  Name: 'Bronze_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 18e3,
  MonsterHPTotal: 10,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestB2', {
  Name: 'Silver_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 36e3,
  MonsterHPTotal: 500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestC2', {
  Name: 'Golden_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 86400,
  MonsterHPTotal: 2e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestD2', {
  Name: 'Legendary_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 345600,
  MonsterHPTotal: 1e5,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestA3', {
  Name: 'Bronze_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 18e3,
  MonsterHPTotal: 10,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestB3', {
  Name: 'Silver_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 36e3,
  MonsterHPTotal: 500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestC3', {
  Name: 'Golden_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 86400,
  MonsterHPTotal: 2e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestD3', {
  Name: 'Legendary_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 345600,
  MonsterHPTotal: 1e5,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestA4', {
  Name: 'Bronze_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 18e3,
  MonsterHPTotal: 10,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestB4', {
  Name: 'Silver_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 36e3,
  MonsterHPTotal: 500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestC4', {
  Name: 'Golden_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 86400,
  MonsterHPTotal: 2e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestD4', {
  Name: 'Legendary_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 345600,
  MonsterHPTotal: 1e5,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestA5', {
  Name: 'Bronze_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 18e3,
  MonsterHPTotal: 10,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestB5', {
  Name: 'Silver_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 36e3,
  MonsterHPTotal: 500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestC5', {
  Name: 'Golden_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 86400,
  MonsterHPTotal: 2e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestD5', {
  Name: 'Legendary_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 345600,
  MonsterHPTotal: 1e5,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestA6', {
  Name: 'Bronze_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 18e3,
  MonsterHPTotal: 10,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestB6', {
  Name: 'Silver_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 36e3,
  MonsterHPTotal: 500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestC6', {
  Name: 'Golden_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 86400,
  MonsterHPTotal: 2e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestD6', {
  Name: 'Legendary_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 345600,
  MonsterHPTotal: 1e5,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestA7', {
  Name: 'Bronze_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 18e3,
  MonsterHPTotal: 10,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestB7', {
  Name: 'Silver_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 36e3,
  MonsterHPTotal: 500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestC7', {
  Name: 'Golden_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 86400,
  MonsterHPTotal: 2e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestD7', {
  Name: 'Legendary_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 345600,
  MonsterHPTotal: 1e5,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestA8', {
  Name: 'Bronze_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 18e3,
  MonsterHPTotal: 10,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestB8', {
  Name: 'Silver_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 36e3,
  MonsterHPTotal: 500,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestC8', {
  Name: 'Golden_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 86400,
  MonsterHPTotal: 2e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('ChestD8', {
  Name: 'Legendary_Chest',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 40,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 345600,
  MonsterHPTotal: 1e5,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 0,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('mushPtutorial', {
  Name: 'Error',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 34,
  MonsterOffsetY: 25,
  HeightOfMonster: 50,
  MonsterMoving: 1,
  MovingFrame: 7,
  DeathFrame: 15,
  RespawnTime: 22,
  MonsterHPTotal: 200,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 200,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 4,
  Damages: [5, 1],
});
ac.addNewMonster('demonPtutorial', {
  Name: 'Error',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 50,
  MonsterOffsetY: 69,
  HeightOfMonster: 68,
  MonsterMoving: 1,
  MovingFrame: 13,
  DeathFrame: 24,
  RespawnTime: 600,
  MonsterHPTotal: 1e4,
  Type: ac.MONSTER_TYPE,
  SpecialType: '_',
  ExpGiven: 5e3,
  ExpType: 0,
  Defence: 1,
  MoveSPEED: 3,
  Damages: [150, 1],
});
ac.addNewMonster('AlienTreetutorial', {
  Name: 'Error',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 32,
  MonsterOffsetY: 0,
  HeightOfMonster: 100,
  MonsterMoving: 0,
  MovingFrame: 1,
  DeathFrame: 6,
  RespawnTime: 0,
  MonsterHPTotal: 5,
  Type: ac.TREE_TYPE,
  SpecialType: '_',
  ExpGiven: 1,
  ExpType: 3,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});
ac.addNewMonster('Starlight', {
  Name: 'Error',
  AFKtype: 'error',
  MonsterFace: 0,
  MonsterOffsetX: 22,
  MonsterOffsetY: 32,
  HeightOfMonster: 25,
  MonsterMoving: 0,
  MovingFrame: 0,
  DeathFrame: 1,
  RespawnTime: 12,
  MonsterHPTotal: 5e4,
  Type: ac.ORE_TYPE,
  SpecialType: '_',
  ExpGiven: 1,
  ExpType: 1,
  Defence: 1,
  MoveSPEED: 0,
  Damages: [0, 1],
});

// update this variable on new patch
module.exports = ac;
